try {
    console.log(nãoExisto)
} catch (error) {
    console.log("Realmente não existe")
    console.log(error)
}